en:
  languageName: English
  weight: 1

es:
  languageName: Español
  weight: 2
  params:
    description: "TODO: A description"
    keywords: 'Hugo, Bootstrap, TODO'
    archive:
      dateFormat: 01-02
